### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by luisrodero-fidesmo** [fidesmo/nfc-reader-mode-bug-example#2]
Create README doc file with the following content/structure: [README.md](https://gist.githubusercontent.com/luisrodero-fidesmo/20c87f22a7dbe363109e22dbe2565af0/raw/bc47d8cac72bafea23899a668c4c1e9b3f2e11fb/README.md)

**Comment by Franzaine** [comment]
The applicable parts were addressed.
